[tool.black]
line-length = 80
target-version = ['py310']
exclude = "(migrations)"

[tool.isort]
py_version = 310
profile = "black"
skip = "migrations"

[tool.pydocstyle]
convention = "numpy"

[tool.mypy]
python_version = "3.10"
allow_untyped_globals = true
follow_imports = "silent"

[[tool.mypy.overrides]]
module = [
	'setuptools.*',
	'decouple.*',
]
ignore_missing_imports = true

[tool.pytest]
mock_use_standalone_module = true

[tool.pytest.ini_options]
minversion = "6.0"
python_files = "tests.py test_*.py *_tests.py tests_*.py"
required_plugins = "pytest-cov"
